version: '3.8'

services:
  todo-app:
    build: .
    container_name: todo-app
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
